#!/bin/sh

# Inspired by "probe" in oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    this_script=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    this_script=$0
else
    this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")

base_dir=${script_dir}/sources/base

build_dir=${script_dir}/$1

. ${script_dir}/sources/poky/oe-init-build-env ${build_dir}

if [ -f ${build_dir}/conf/append_complete ]; then
    return 1
fi

# Board specific entries
cp ${base_dir}/templates/bblayers.conf.sample ${build_dir}/conf/bblayers.conf
cat >> ${build_dir}/conf/local.conf <<EOF
DL_DIR = "\${TOPDIR}/../downloads/"
SSTATE_DIR = "\${TOPDIR}/../sstate-cache/"
EOF
cat ${base_dir}/templates/local.conf.append >> ${build_dir}/conf/local.conf

touch ${build_dir}/conf/append_complete

